import { ExpertAgent, AssistantAgent } from "./types";

function createAssistant(
  id: string,
  nameAr: string,
  nameEn: string,
  role: string
): AssistantAgent {
  return {
    id,
    nameAr,
    nameEn,
    role,
    status: "idle",
    accuracy: 65 + Math.random() * 30,
    lastActive: new Date().toISOString(),
  };
}

export function createAgentRegistry(): ExpertAgent[] {
  return [
    {
      id: "ceo",
      nameAr: "المدير العام",
      nameEn: "CEO Manager",
      category: "ceo",
      role: "التنسيق النهائي وصياغة القرار",
      description: "يوازن بين آراء الخبراء ويستخدم خوارزمية الترجيح لاتخاذ القرار النهائي. يستخدم Ensemble Methods للوصول لدقة 95%",
      icon: "👑",
      color: "#FFD700",
      status: "idle",
      accuracy: 88,
      weight: 1.0,
      assistants: [
        createAssistant("ceo-1", "منسق الاجتماعات", "Meeting Coordinator", "جمع تقارير جميع الخبراء وتنظيمها"),
        createAssistant("ceo-2", "كاتب التقارير النهائي", "Report Writer", "صياغة القرار بلغة بشرية واضحة"),
        createAssistant("ceo-3", "مراقب جودة القرار", "Decision Quality Monitor", "تقييم دقة القرارات التاريخية"),
        createAssistant("ceo-4", "أرشيفي القرارات", "Decision Archiver", "حفظ كل قرار وأسبابه للرجوع المستقبلي"),
        createAssistant("ceo-5", "مترجم المستخدم", "User Translator", "فهم أسلوب المستخدم والتكيف معه"),
        createAssistant("ceo-6", "محرك القرار النهائي", "Final Decision Engine", "تطبيق Ensemble Methods وتصويت مرجح متقدم"),
      ],
    },
    {
      id: "fundamental",
      nameAr: "الخبير المالي الأساسي",
      nameEn: "Fundamental Analyst",
      category: "fundamental",
      role: "تحليل صحة الأصول من الداخل",
      description: "يحلل القوائم المالية والتقارير والنسب المالية لتحديد القيمة العادلة بدقة عالية",
      icon: "📊",
      color: "#3B82F6",
      status: "idle",
      accuracy: 82,
      weight: 0.15,
      assistants: [
        createAssistant("fund-1", "محلل القطاعات الصناعية", "Sector Analyst", "يركز على قطاع محدد (تقنية، طاقة، صحة)"),
        createAssistant("fund-2", "خبير سلاسل التوريد", "Supply Chain Expert", "يحلل سلاسل الإمداد العالمية للشركات"),
        createAssistant("fund-3", "مقيم الأصول العادل", "Fair Value Assessor", "يحسب القيمة الجوهرية بدقة (DCF, Comparables, PE)"),
        createAssistant("fund-4", "مراقب المنافسين", "Competitor Monitor", "يحلل أداء الشركات المنافسة"),
        createAssistant("fund-5", "خبير العلاقات المستثمرية", "IR Analyst", "يحلل تقارير اجتماعات المساهمين"),
        createAssistant("fund-6", "محلل القوائم المالية المتقدم", "Advanced Financial Analyst", "تحليل EBITDA, FCF, EV/EBITDA, PEG"),
        createAssistant("fund-7", "خبير تقييم الأسهم الناشئة", "Growth Stock Analyst", "تخصيص لتحليل شركات النمو والتقنية"),
      ],
    },
    {
      id: "news",
      nameAr: "خبير الأخبار والمشاعر",
      nameEn: "News & Sentiment Analyst",
      category: "news",
      role: "قياس نبض السوق النفسي والأخبار العاجلة",
      description: "يحلل الأخبار ووسائل التواصل باستخدام NLP متقدم لقياس المشاعر بدقة 90%+",
      icon: "📰",
      color: "#EF4444",
      status: "idle",
      accuracy: 78,
      weight: 0.12,
      assistants: [
        createAssistant("news-1", "كاشف الأخبار المزيفة", "Fake News Detector", "يتحقق من مصدر الخبر ومصداقيته بالذكاء الاصطناعي"),
        createAssistant("news-2", "محلل لهجات الخطاب", "Tone Analyzer", "يدرس نبرة تصريحات المسؤولين"),
        createAssistant("news-3", "مراقب وسائل التواصل", "Social Media Monitor", "يحلل تويتر ورديت وتيليجرام"),
        createAssistant("news-4", "مترجم الأخبار العاجلة", "News Translator", "يترجم الأخبار من لغات متعددة (صيني، ياباني، عربي، إنجليزي)"),
        createAssistant("news-5", "أرشيفي الأحداث التاريخية", "Historical Events Archiver", "يقارن الخبر الحالي بأحداث تاريخية مشابهة"),
        createAssistant("news-6", "محلل تأثير البنوك المركزية", "Central Bank Impact Analyst", "يحلل قرارات الفائدة وتأثيرها على الأصول"),
      ],
    },
    {
      id: "technical",
      nameAr: "خبير الاستراتيجيات الفنية",
      nameEn: "Technical Strategy Analyst",
      category: "technical",
      role: "تحليل الرسوم البيانية والأنماط السعرية بـ 15+ استراتيجية",
      description: "يحلل المؤشرات الفنية والأنماط باستخدام استراتيجيات متقدمة: Ichimoku, SMC, Elliott Wave, Fibonacci, VWAP, Market Profile",
      icon: "📈",
      color: "#10B981",
      status: "idle",
      accuracy: 85,
      weight: 0.2,
      assistants: [
        createAssistant("tech-1", "صياد الأنماط السعرية", "Pattern Hunter", "يكتشف أنماط الشموع والرسوم الكلاسيكية (Head&Shoulders, Double Top)"),
        createAssistant("tech-2", "خبير مستويات الدعم والمقاومة", "S/R Expert", "يرسم مستويات السعر الرئيسية تلقائياً"),
        createAssistant("tech-3", "محلل أحجام التداول", "Volume Analyst", "يدرس Volume Profile و Order Flow"),
        createAssistant("tech-4", "خبير التوقيت الدقيق", "Timing Expert", "يحلل أفضل أوقات التداول لكل جلسة"),
        createAssistant("tech-5", "مختبر الاستراتيجيات", "Strategy Tester", "يختبر 100+ استراتيجية على البيانات التاريخية"),
        createAssistant("tech-6", "خبير SMC والمال الذكي", "SMC Expert", "يدرس Order Blocks, Liquidity Pools, Fair Value Gaps"),
        createAssistant("tech-7", "خبير موجات إليوت", "Elliott Wave Expert", "يحلل دورة الموجات وتحديد🏤ة الحالية"),
        createAssistant("tech-8", "خبير إيشيموكو", "Ichimoku Expert", "تحليل شامل بنظام إيشيموكو المتقدم"),
        createAssistant("tech-9", "خبير فيبوناتشي المتقدم", "Fibonacci Expert", "مستويات فيبوناتشي والامتدادات والوقت"),
        createAssistant("tech-10", "خبير ملف السوق", "Market Profile Expert", "تحليل TPO و POC و Value Area"),
      ],
    },
    {
      id: "risk",
      nameAr: "خبير الحسابات وإدارة المخاطر",
      nameEn: "Risk & Accounting Agent",
      category: "risk",
      role: "حارس المال - يملك حق الفيتو المطلق",
      description: "يحدد حجم الصفقة المثالي (Kelly Criterion) ونقطة وقف الخسارة ويراقب التعرض الكلي. لا يسمح بأي صفقة تخاطر بأكثر من 2%",
      icon: "🛡️",
      color: "#F59E0B",
      status: "idle",
      accuracy: 93,
      weight: 0.2,
      assistants: [
        createAssistant("risk-1", "حارس وقف الخسارة", "Stop Loss Guardian", "يراقب ويعدل أوامر وقف الخسارة تلقائياً (Trailing Stop)"),
        createAssistant("risk-2", "محفظ التنويع", "Diversification Manager", "يوزع المخاطر عبر أصول غير مترابطة"),
        createAssistant("risk-3", "حاسبة الرسوم الضمنية", "Fee Calculator", "يحسب العمولات والسبريد والضرائب والأثر على الربح الصافي"),
        createAssistant("risk-4", "مراقب التعرض الكلي", "Exposure Monitor", "يحسب التعرض الإجمالي لجميع الصفقات والعملات"),
        createAssistant("risk-5", "خبير التحوط", "Hedging Expert", "يقترح صفقات عكسية (ذهب، سندات، Put Options)"),
        createAssistant("risk-6", "حاسب معيار كيلي", "Kelly Criterion Calculator", "يحسب نسبة المخاطرة المثالية بناءً على تاريخ الأداء"),
        createAssistant("risk-7", "محلل الارتباط", "Correlation Analyst", "يحلل ارتباط الأصول لتجنب التعرض المزدوج"),
      ],
    },
    {
      id: "system",
      nameAr: "الخبير البرمجي والنظامي",
      nameEn: "System & Code Agent",
      category: "system",
      role: "مراقبة صحة النظام والبنية التحتية",
      description: "يراقب سجلات الأخطاء وسرعة التنفيذ واستهلاك الموارد وضمان جودة البيانات",
      icon: "⚙️",
      color: "#8B5CF6",
      status: "idle",
      accuracy: 96,
      weight: 0.05,
      assistants: [
        createAssistant("sys-1", "حارس الأمن السيبراني", "Cybersecurity Guard", "يراقب محاولات الاختراق ويؤمن المفاتيح"),
        createAssistant("sys-2", "مراقب جودة البيانات", "Data Quality Monitor", "يتأكد من دقة بيانات السوق ويكشف الفجوات"),
        createAssistant("sys-3", "محسن سرعة التنفيذ", "Execution Optimizer", "يقلل زمن التأخير بين القرار والتنفيذ"),
        createAssistant("sys-4", "مدير النسخ الاحتياطي", "Backup Manager", "ينسخ كل البيانات والاستراتيجيات تلقائياً"),
        createAssistant("sys-5", "كاشف الأعطال المبكر", "Early Fault Detector", "يتنبأ بالأعطال قبل وقوعها (الذاكرة، الشبكة)"),
        createAssistant("sys-6", "مراقب أداء APIs", "API Performance Monitor", "يراقب سرعة واستقرار مصادر البيانات الخارجية"),
      ],
    },
    {
      id: "decision",
      nameAr: "خبير القرارات وعلم النفس",
      nameEn: "Decision & Psychology Agent",
      category: "decision",
      role: "محاكاة العقل البشري الواعي ومنع القرارات الانفعالية",
      description: "يقيس ثقة النظام ويمنع التحيزات المعرفية والقرارات العاطفية. يحلل سلوك المستخدم",
      icon: "🧠",
      color: "#EC4899",
      status: "idle",
      accuracy: 85,
      weight: 0.13,
      assistants: [
        createAssistant("psych-1", "محلل أخطائك التاريخية", "Historical Error Analyst", "يكتشف أنماط الخسائر السابقة ويحذر"),
        createAssistant("psych-2", "كاشف التحيزات المعرفية", "Cognitive Bias Detector", "يكتشف: تأكيد، مغامرة، تشبث، قطيع"),
        createAssistant("psych-3", "مدير الجرعات التداولية", "Trading Dosage Manager", "يحدد عدد الصفقات المسموح بها يومياً"),
        createAssistant("psych-4", "مهدئ ما بعد الخسارة", "Post-Loss Calmer", "يفرض هدوء إجباري 24 ساعة بعد 3 خسائر متتالية"),
        createAssistant("psych-5", "محفز الانضباط", "Discipline Motivator", "يكافئ الالتزام بالخطة ويعزز السلوك الإيجابي"),
        createAssistant("psych-6", "محلل FOMO", "FOMO Analyzer", "يكتشف خوف الفوت ويمنع الشراء الانفعالي"),
      ],
    },
    {
      id: "audit",
      nameAr: "خبير التدقيق والمراجعة الداخلية",
      nameEn: "Internal Audit Agent",
      category: "audit",
      role: "مراجعة أداء جميع الخبراء - حق الفيتو والإيقاف الطارئ",
      description: "يكتشف التحيزات والتناقضات وانتهاكات الامتثال. يملك حق إيقاف النظام بالكامل عند الخطر الجسيم",
      icon: "🔍",
      color: "#6366F1",
      status: "idle",
      accuracy: 94,
      weight: 0.15,
      assistants: [
        createAssistant("audit-1", "مراقب أداء الخبراء", "Expert Performance Monitor", "تقييم مستمر لدقة كل خبير وتعديل الأوزان"),
        createAssistant("audit-2", "كاشف التناقضات", "Contradiction Detector", "رصد التعارض بين تقارير الخبراء"),
        createAssistant("audit-3", "مدقق الامتثال الداخلي", "Internal Compliance Auditor", "ضمان التزام النظام بالقواعد الداخلية"),
        createAssistant("audit-4", "محلل الانحرافات", "Anomaly Analyzer", "اكتشاف السلوك غير الطبيعي (اختراق أو خلل)"),
        createAssistant("audit-5", "مقيّم جودة البيانات", "Data Quality Assessor", "التحقق من صحة البيانات قبل المعالجة"),
        createAssistant("audit-6", "مدقق استراتيجيات التعلم", "Learning Strategy Auditor", "يتأكد من أن تحديثات التعلم تحسن الأداء وليس العكس"),
      ],
    },
  ];
}

export const agentRegistry = createAgentRegistry();
export const totalAgents = agentRegistry.length + agentRegistry.reduce((s, e) => s + e.assistants.length, 0);
